# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # - image: circleci/node:7.10
      - image: circleci/node:9.5-browsers

      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - run:
          name: Rebuild native dependencies
          command: npm rebuild
          when: on_fail

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Starting node server
          command: mkdir logs && yarn start
          background: true

      - run:
          name: View IP address
          command: node -p "require('ip').address()"

      - run:
          name: Storing local IP address
          command: node -p "require('ip').address()" > logs/ip.log

      - run:
          name: waiting for node server to start
          command: wget --retry-connrefused --waitretry=2 -t 5 "http://$(cat logs/ip.log)" > /dev/null

      - run:
          name: running tests
          command: yarn test

      - store_artifacts:
          path: logs

workflows:
  version: 2
  build:
    jobs:
      - build
